image: node:10.12.0-stretch

variables:
  # Use development to enable logging
  NODE_ENV: development

stages:
- setup
- build
- testing
- predeploy

backend-install:
  stage: setup
  image: node:10.12.0-stretch
  variables:
    NODE_ENV: development
  script:
  - npm install
  only:
  - branches
  artifacts:
    expire_in: 1 week
    paths:
    - node_modules

frontend-install:
  stage: setup
  image: node:10.12.0-stretch
  variables:
    NODE_ENV: development
  script:
  - npm install --prefix './client'
  only:
  - branches
  artifacts:
    expire_in: 1 week
    paths:
    - client/node_modules

backend-lint:
  stage: testing
  image: node:10.12.0-stretch
  script:
  - npm run lint
  only:
  - branches

frontend-lint:
  stage: testing
  image: node:10.12.0-stretch
  script:
  - npm run lint --prefix './client'
  only:
  - branches

frontend-test:
  stage: testing
  image: node:10.12.0-stretch
  script:
  - npm run test:coverage --prefix './client'
  only:
  - branches

# Build the front-end to ensure the size limit isn't reached etc
frontend-build:
  stage: predeploy
  image: node:10.12.0-stretch
  script:
  - npm run build:prod --prefix './client' || true
