export const FETCH_ACTOR_DETAILS_REQUESTED = 'FETCH_ACTOR_DETAILS_REQUESTED';
export const FETCH_ACTOR_DETAILS_SUCCESS = 'FETCH_ACTOR_DETAILS_SUCCESS';
export const FETCH_ACTOR_DETAILS_FAILED = 'FETCH_ACTOR_DETAILS_FAILED';
