export const FETCH_MEDIA_DETAILS_REQUESTED = 'FETCH_MEDIA_DETAILS_REQUESTED';
export const FETCH_MEDIA_DETAILS_SUCCESS = 'FETCH_MEDIA_DETAILS_SUCCESS';
export const FETCH_MEDIA_DETAILS_FAILED = 'FETCH_MEDIA_DETAILS_FAILED';
export const SEARCH_MEDIA = 'SEARCH_MEDIA';
