export const FETCH_MEDIA_DETAILS_REQUESTED = 'FETCH_MEDIA_DETAILS_REQUESTED';
export const FETCH_MEDIA_DETAILS_SUCCESS = 'FETCH_MEDIA_DETAILS_SUCCESS';
export const FETCH_MEDIA_DETAILS_FAILED = 'FETCH_MEDIA_DETAILS_FAILED';

export const SEARCH_MEDIA_REQUESTED = 'SEARCH_MEDIA_REQUESTED';
export const SEARCH_MEDIA_SUCCESS = 'SEARCH_MEDIA_SUCCESS';
export const SEARCH_MEDIA_FAILED = 'SEARCH_MEDIA_FAILED';

export const UPDATE_SEARCH_FIELDS = 'UPDATE_SEARCH_FIELDS';

export const ADD_MEDIA_COMMENT_REQUESTED = 'ADD_MEDIA_COMMENT_REQUESTED';
export const ADD_MEDIA_COMMENT_SUCCESS = 'ADD_MEDIA_COMMENT_SUCCESS';
export const ADD_MEDIA_COMMENT_FAILED = 'ADD_MEDIA_COMMENT_FAILED';
